# Generated by Django 4.2.4 on 2023-10-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_lido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tamanho',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, verbose_name='Tamanho do PET'),
        ),
    ]
