# Generated by Django 4.2.4 on 2023-11-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_categoria_reserva_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petshop',
            options={'verbose_name': 'Petshop Cadastrado', 'verbose_name_plural': 'Petshops Cadastrados'},
        ),
    ]
