# Generated by Django 4.2.4 on 2023-11-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_petshop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petshop',
            options={'ordering': ['id'], 'verbose_name': 'Petshop Cadastrado', 'verbose_name_plural': 'Petshops Cadastrados'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['id'], 'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reservas de Banho'},
        ),
    ]
